# Generated by Django 5.2.8 on 2025-12-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_homeslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='deal_thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='DealOfTheMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Deal of the Month', max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('main_product_name', models.CharField(max_length=255)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('main_image', models.ImageField(upload_to='deals/')),
                ('timer_end', models.DateTimeField(blank=True, null=True)),
                ('thumbnail_images', models.ManyToManyField(blank=True, to='accounts.dealthumbnail')),
            ],
        ),
    ]
