# Generated by Django 5.2.8 on 2025-12-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_galleryitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryItem',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
