# Generated by Django 5.2.7 on 2025-12-12 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='qr_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='qr_payments/'),
            preserve_default=False,
        ),
    ]
