# Generated by Django 5.2.7 on 2025-12-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_paymentmethods_delete_galleryimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetail',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
