# Generated by Django 5.2.7 on 2025-12-23 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_billingdetail_payment_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetail',
            name='payment_link',
        ),
    ]
