# Generated by Django 5.2.7 on 2025-12-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='singleContent',
            field=models.TextField(null=True),
        ),
    ]
